- name: Send request to API (keypair show)
  uri:
    url: "{{ AUTH_URL_ECS }}/os-keypairs/{{ ecs_adminkey }}"
    method: GET
    return_content: true
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: keypairdetail
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: keypairdetail.status == 200
  changed_when: false

- name: keypairdetail
  debug:
    msg: "{{ keypairdetail.json }}"
